/*
 * Generated by XDoclet - Do not edit!
 */
package open.dolphin.spring.model.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import open.dolphin.spring.model.core.InfoModel;

import javax.persistence.*;

/**
 * RadiologyMethodValue
 *
 * @author Minagawa,kazushi
 *
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Entity
@Table(name = "d_radiology_method")
public class RadiologyMethodValue extends InfoModel {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private int id;

    private String hierarchyCode1;

    private String hierarchyCode2;

    private String methodName;

    @Override
    public String toString() {
        return methodName;
    }

    @Override
    public int hashCode() {
        final int PRIME = 31;
        int result = 1;
        result = PRIME * result + id;
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final RadiologyMethodValue other = (RadiologyMethodValue) obj;
        if (id != other.id)
            return false;
        return true;
    }
}
